language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/clover.xml
  - '[[ $TRAVIS_PHP_VERSION = hhvm ]] || php build/coverage-checker.php build/clover.xml 70'
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.3' ]; then ./vendor/bin/phpcs --standard=vendor/doctrine/coding-standard/Doctrine ./src/ ./tests/; fi"

after_script:
  - |
    [[ $TRAVIS_PHP_VERSION = hhvm ]] || {
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover ./build/clover.xml
    }
